### ISSUE TITLE
本地运行报错~   Cannot read property 'Promise' of undefined   TypeError: Cannot read property 'Promise' of undefined

### ISSUE THREAD

**Issue by zhubenjie** [dyq086/wepy-mall#31]
```javascript
Cannot read property 'Promise' of undefined 
 TypeError: Cannot read property 'Promise' of undefined
    at http://127.0.0.1:50218/appservice/npm/wepy-async-function/index.js:14:7
    at require (http://127.0.0.1:50218/appservice/__dev__/WAService.js:18:26712)
    at `
```
```javascript
var g = require('./global.js');

if (!g.Promise) {
  // IOS 10.0.1 may cause IOS crash.
  g.Promise = require('./../promise-polyfill/promise.js');
}
if (!g.regeneratorRuntime) {
  g.regeneratorRuntime = require('./../regenerator-runtime/runtime.js');
}
```
node 版本8.5

**Comment by jianjiandandan** [comment]
app.wpy 里面加入import 'wepy-async-function'   
  constructor() {
    super()
    this.use('promisify');
  }

这样就不报了

**Comment by KTDefTnT** [comment]
我这个也报错这个  app.wpy里面也import了

**Comment by 799677446** [comment]
请问下问题处理了吗，我这边也报这个错

**Comment by dadajuzi** [comment]
微信开发者工具右边扩展箭头 -> 详情 -> ES6转ES5取消勾选
