### ISSUE TITLE
问题列表

### ISSUE THREAD

**Issue by alexsz2012** [dyq086/wepy-mall#58]
按你步骤上的解释跑不前啊
问题列表
1.  安装提示没有less模块，需要手动重新安装一次less
2.  开发者工具导入dist目录后报错
thirdScriptError 
 sdk uncaught third Error 
 module "npm/wepy/lib/native.js" is not defined 
 Error: module "npm/wepy/lib/native.js" is not defined

**Comment by Nisus-Liu** [comment]
没人解决吗?

**Comment by Nisus-Liu** [comment]
我编译 `wepy-weui-demo` 报: 
```
thirdScriptError 
 sdk uncaught third Error 
 module "npm/wepy/lib/native.js" is not defined 
 Error: module "npm/wepy/lib/native.js" is not defined
```

**Comment by boychina** [comment]
es6: 对应关闭ES6转ES5选项，关闭。 重要：未关闭会运行报错。

postcss: 对应关闭上传代码时样式自动补全选项，关闭。 重要：某些情况下漏掉此项也会运行报错。

minified: 对应关闭代码压缩上传选项，关闭。重要：开启后，会导致真机computed, props.sync 等等属性失效。（注：压缩功能可使用WePY提供的build指令代替，详见后文相关介绍以及Demo项目根目录中的wepy.config.js和package.json文件。）

urlCheck: 对应不检查安全域名选项，开启。 如果已配置好安全域名则建议关闭。

https://tencent.github.io/wepy/document.html#/

这里用了wepy，需要在开发者工具里进行设置。

**Comment by dashankeji** [comment]
[WARNING] 找不到编译器：wepy-compiler-less。
[Error] 未发现相关 less 编译器配置，请检查wepy.config.js文件。

搞什么鬼

**Comment by cfangxx** [comment]
跑不通,问题不少

**Comment by cfangxx** [comment]
The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal,

**Comment by cfangxx** [comment]
@dashankeji npm install less

**Comment by Master-gg-02** [comment]
问题 一：
执行  cnpm install wepy-cli -g
报错： WARN node unsupported "node@v11.3.0" is incompatible with update-notifier@1.0.3                                                                                                                  › latest-version@2.0.0 › package-json@2.4.0 › got@^5.0.0, expected node@>=0.10.0                                                                                                                  <7                                                                                                                                                                                              [25/30] update-notifier@^1.0.2 installed at node_modules\_update-notifier@1.0.3@                                                                                                                 update-notifier
--   （node版本不兼容）

我直接忽略了  
 接着执行  cnpm install（安装依赖）
--
出现问题二 ：

WARN node unsupported "node@v11.3.0" is incompatible with wepy-plugin-imagemin@1                                                                                                                 .5.3 › imagemin-pngquant@5.1.0 › pngquant-bin@4.0.0 › bin-wrapper@3.0.2 › downlo                                                                                                                 ad@4.4.3 › got@^5.0.0, expected node@>=0.10.0 <7                                                                                                                                                                                                                                                                                                                                                  WARN node unsupported "node@v11.3.0" is incompatible with eslint@>=4.18.2, expec                                                                                                                 ted node@^8.10.0 \|\| ^10.13.0 \|\| >=11.10.1
--（node版本不兼容）
依然直接忽略

执行 npm run build
问题三 

{ Error: Cannot find module 'less'                                                                                                                                                                   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)                                                                                                                      at Function.Module._load (internal/modules/cjs/loader.js:529:25)                                                                                                                                 at Module.require (internal/modules/cjs/loader.js:658:17)                                                                                                                                        at require (internal/modules/cjs/helpers.js:22:18)                                                                                                                                               at Object. (D:\test\wepy-mall\node_modules\_wepy-compiler-less@1.                                                                                                                 3.14@wepy-compiler-less\lib\index.js:20:13)                                                                                                                                                          at Module._compile (internal/modules/cjs/loader.js:722:30)                                                                                                                                       at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)                                                                                                                         at Module.load (internal/modules/cjs/loader.js:620:32)                                                                                                                                           at tryModuleLoad (internal/modules/cjs/loader.js:560:12)                                                                                                                                         at Function.Module._load (internal/modules/cjs/loader.js:552:3)                                                                                                                                  at Module.require (internal/modules/cjs/loader.js:658:17)                                                                                                                                        at require (internal/modules/cjs/helpers.js:22:18)                                                                                                                                               at Object.load (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy                                                                                                                 -cli\lib\loader.js:113:17)                                                                                                                                                                           at Object.loadCompiler (C:\Users\Administrator\AppData\Roaming\npm\node_modu                                                                                                                 les\wepy-cli\lib\loader.js:69:29)                                                                                                                                                                    at Object.checkCompiler (C:\Users\Administrator\AppData\Roaming\npm\node_mod                                                                                                                 ules\wepy-cli\lib\compile.js:178:35)                                                                                                                                                                 at Object.init (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy                                                                                                                 -cli\lib\compile.js:221:19) code: 'MODULE_NOT_FOUND' }                                                                                                                                           [WARNING] 找不到编译器：wepy-compiler-less。                                                                                                                                                     [16:11:07] [错误] 不存在插件：wepy-compiler-less，请检测是否拼写错误。                                                                                                                           { Error: Command failed: npm info wepy-compiler-less                                                                                                                                             npm ERR! code ECONNRESET                                                                                                                                                                         npm ERR! errno ECONNRESET                                                                                                                                                                        npm ERR! syscall read                                                                                                                                                                            npm ERR! network read ECONNRESET                                                                                                                                                                 npm ERR! network This is a problem related to network connectivity.                                                                                                                              npm ERR! network In most cases you are behind a proxy or have bad network settings.                                                                                                              npm ERR! network                                                                                                                                                                                 npm ERR! network If you are behind a proxy, please make sure that the                                                                                                                            npm ERR! network 'proxy' config is set properly.  See: 'npm help config'                                                                                                                                                                                                                                                                                                                          npm ERR! A complete log of this run can be found in:                                                                                                                                             npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-08-24T08_11_07_541Z-debug.log                                                                                                                                                                                                                                                                                                at ChildProcess.exithandler (child_process.js:294:12)                                                                                                                                            at ChildProcess.emit (events.js:182:13)                                                                                                                                                          at maybeClose (internal/child_process.js:978:16)                                                                                                                                                 at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)                                                                                                                       killed: false,                                                                                                                                                                                   code: 1,                                                                                                                                                                                         signal: null,                                                                                                                                                                                    cmd: 'npm info wepy-compiler-less' }
--（缺少  ’wepy-compiler-less' 这个包）
安装这个包执行  cnpm i wepy-compiler-less -dev
--

接着执行 npm  run build 
最后问题成这样了


removed 2199 packages in 50.704s                                                                                                                                                                 [16:14:11] [完成] 已完成安装 wepy-compiler-less，重新启动编译。                                                                                                                                  [16:14:12] [编译] 入口: src\app.wpy                                                                                                                                                              [16:14:12] [写入] JSON: dist\app.json                                                                                                                                                            { Error: Cannot find module 'less'                                                                                                                                                                   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)                                                                                                                      at Function.Module._load (internal/modules/cjs/loader.js:529:25)                                                                                                                                 at Module.require (internal/modules/cjs/loader.js:658:17)                                                                                                                                        at require (internal/modules/cjs/helpers.js:22:18)                                                                                                                                               at Object. (D:\test\wepy-mall\node_modules\_wepy-compiler-less@1.3.14@wepy-compiler-less\lib\index.js:20:13)                                                                          at Module._compile (internal/modules/cjs/loader.js:722:30)                                                                                                                                       at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)                                                                                                                         at Module.load (internal/modules/cjs/loader.js:620:32)                                                                                                                                           at tryModuleLoad (internal/modules/cjs/loader.js:560:12)                                                                                                                                         at Function.Module._load (internal/modules/cjs/loader.js:552:3)                                                                                                                                  at Module.require (internal/modules/cjs/loader.js:658:17)                                                                                                                                        at require (internal/modules/cjs/helpers.js:22:18)                                                                                                                                               at Object.load (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\loader.js:113:17)                                                                                           at Object.loadCompiler (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\loader.js:69:29)                                                                                    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile-style.js:91:45                                                                                                   at Array.forEach () code: 'MODULE_NOT_FOUND' }                                                                                                                                    [WARNING] 找不到编译器：wepy-compiler-less。                                                                                                                                                     [Error] 未发现相关 less 编译器配置，请检查wepy.config.js文件。
--

**Comment by Primary-Traxex** [comment]
`Unknown plugin "transform-class-properties" specified in "base" at 0, attempted to resolve relative to "D:\\projects\\wepy-mall"`
上面这个不知道什么错误
